# Generated by Django 2.2.10 on 2022-01-13 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreateSurvey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey_name', models.CharField(max_length=255, verbose_name='Название опроса')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Описание опроса')),
                ('publication_date', models.DateTimeField(help_text='Формат даты: ГГГГ-ММ-ДД, Формат времени: ЧЧ:ММ', verbose_name='Дата начала опроса')),
                ('end_date', models.DateTimeField(help_text='format: ГГГГ-ММ-ДД, Формат времени: ЧЧ:ММ', verbose_name='Дата окончания опроса')),
            ],
            options={
                'verbose_name': 'Опрос',
                'verbose_name_plural': 'Опрос',
            },
        ),
        migrations.CreateModel(
            name='CreateSurveyQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=255)),
                ('question_type', models.CharField(choices=[('TEXT', 'TEXT'), ('CHOICE', 'CHOICE'), ('MULTICHOICE', 'MULTICHOICE')], default='TEXT', max_length=11)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='surveys.CreateSurvey')),
            ],
            options={
                'verbose_name_plural': 'Вопросы',
            },
        ),
        migrations.CreateModel(
            name='ChoiceAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=255)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='surveys.CreateSurveyQuestion')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('answer_text', models.CharField(max_length=255)),
                ('choice_answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choice', to='surveys.ChoiceAnswer')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question', to='surveys.CreateSurveyQuestion')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey', to='surveys.CreateSurvey')),
            ],
            options={
                'verbose_name_plural': 'Ответы',
            },
        ),
    ]
